### ISSUE TITLE
Feature Wish: Jack Transport 

### ISSUE THREAD

**Issue by nilsgey** [jeremyevans/aqualung#1]
It is great that aqualung support the jack audio connection kit as output.
Could you implement jack transport, please? 
Then it would be possible to start and run several instances of aqualung with gapless playlists simultaneously in sync. Useful for experimental, randomized, multi-track audio-generation on the fly.

Thanks in advance!

**Comment by jeremyevans** [comment]
Aqualung is feature complete, in the sense that no future features are planned.  If the `--with-jack` configuration option doesn't already do what you need, I'm afraid you will not be able to use Aqualung for this.
