### ISSUE TITLE
Failed to build 1.1 with libifp

### ISSUE THREAD

**Issue by mokkurkalve** [jeremyevans/aqualung#19]
I tried to build aqualung 1.1 using this package https://aur.archlinux.org/packages/aqualung-git/
This was on Arch Linux current with kernel 5.8.5, gcc 10.2.0 and libifp 1.0.0.2.
The build errs out like this: https://pastebin.com/exJXH82f
After uninstalling libifp the build went just fine.

**Comment by jeremyevans** [comment]
@atsampson This appears to be related to your string handling changes, any idea?

**Comment by atsampson** [comment]
Yes, that looks like my fault (although at least `CHAR_ARRAY_SIZE` caught the error!). I'll have a look...
