### ISSUE TITLE
Podcasts feed doesn't update.

### ISSUE THREAD

**Issue by khadegd** [jeremyevans/aqualung#21]
I get the following error.
`podcast_generic_download: httpc_init failed, ret = -1`

**Comment by khadegd** [comment]
Hidden Brain from NPR - `https://feeds.npr.org/510308/podcast.xml`

**Comment by jeremyevans** [comment]
I can reproduce this issue. Looks like the podcast support is currently only for `http` and not `https`.  Aqualung doesn't link to an SSL library, so that kind of makes sense.  I'll make sure this is documented.
