### ISSUE TITLE
Add HTTPS support for radio streams

### ISSUE THREAD

**Issue by v2e** [jeremyevans/aqualung#27]
Currently it is impossible to add the HTTPS URL to Aqualung playlist. It would be great to be able to listen to online radio streams using HTTPS protocol.

Many servers abandon the HTTP protocol and redirect the HTTP URLs to the HTTPS version. Here is an example of radio stream that is accessible through HTTPs only: [https://radio-stream-1.obozrevatel.com/sheshory128.ogg](https://radio-stream-1.obozrevatel.com/sheshory128.ogg)

If I open this URL in browser, it plays, but I cannot add it to Aqualung.

**Comment by jeremyevans** [comment]
Aqualung does not link to an SSL library, so this is currently not possible, and there are no plans to add this feature.  However, we would consider a pull request that adds support via a configure flag (off by default).

**Comment by m1k3s0** [comment]
Hi, I'm curious why there are no plans to add this feature? I really enjoy using Aqualung and would like to be able to play radio streams in it as well. Most popular music streams (include SomaFM) use TLS now.

**Comment by ciotog** [comment]
You can implement this locally using a reverse proxy configuration with nginx

**Comment by m1k3s0** [comment]
Are you suggesting I run a server just to stream audio?

**Comment by ciotog** [comment]
Just offering a solution, if you think it's unreasonable then you're free to not do it

**Comment by jeremyevans** [comment]
Aqualung is basically in maintenance mode, no new features are planned, though we will accept pull requests to fix bugs and implement new features.

**Comment by m1k3s0** [comment]
Ok, thanks.

**Comment by atsampson** [comment]
The reason it doesn't work at the moment is that aqualung has its own HTTP client code, which made sense when it was originally written but isn't best practice these days. Making it use [libsoup](https://libsoup.org/libsoup-3.0/client-basic.html) instead would add support for HTTPS etc., and let us get rid of some fairly complex code for parsing URLs and HTTP responses.

**Comment by m1k3s0** [comment]
So…you’re saying there’s a chance? 😆

**Comment by m1k3s0** [comment]
One lightweight workaround that I discovered if anyone is interested. You can use streamripper...

`streamripper <https://stream-url> -A -r -u myagent`

The -A will disable saving to disk, the -r will rebroadcast locally on port 8000, and the -u will use a fake user-agent. Then you can add http://localhost:8000 as the stream url.

**Comment by ciotog** [comment]
That should work well. One caveat - streamripper will continuously consume while it's running, whether or not you're actively using the stream with Aqualung. Using nginx as a proxy would allow it to work on demand.
