### ISSUE TITLE
Support for newer versions of Monkey's Audio

### ISSUE THREAD

**Issue by billie80** [jeremyevans/aqualung#33]
I recognise that aqualung is in low maintenance mode. However I still would like to know if it is possible to add support for newer versions of [Monkey's Audio](https://monkeysaudio.com/). If not I have to think about disabling mac support in the [Gentoo ebuild](https://bugs.gentoo.org/838715).

It might be helpful that for [Fedora](https://src.fedoraproject.org/rpms/aqualung/tree/rawhide) there are patches available to make aqualung work with the newer versions.

I tried the patch from Fedora but it fails here with Monkey's Audio 10.18. I tried to fix it and there was some success but in the end I am struggling with linking errors:

> /usr/lib/gcc/x86_64-pc-linux-gnu/12/../../../../x86_64-pc-linux-gnu/bin/ld: decoder/aqualung-dec_mac.o: in function `mac_decoder_open':
> dec_mac.cpp:(.text+0x179): undefined reference to `CreateIAPEDecompress'

I will attach my attempts as patches. Hope it helps.
[aqualung-1.2-mac-configure.patch.txt](https://github.com/jeremyevans/aqualung/files/12330235/aqualung-1.2-mac-configure.patch.txt)
~~[aqualung-1.2-mac-dec.patch.txt](https://github.com/jeremyevans/aqualung/files/12330236/aqualung-1.2-mac-dec.patch.txt)~~

**Comment by jeremyevans** [comment]
I'd be happy to accept a pull request for this that was backwards compatible with the current version.  However, this is not something I'm interested in working on personally.

**Comment by billie80** [comment]
I understand.

Unfortunately this is what I got so far. I am no programmer thus getting there took a lot of time. Maybe you can give me a hint regarding the linking issue. Then at least a non backwards compatible patch (pull request) would be possible.

I don't think I am capable of making this backwards compatible without again spending a lot of time. Is it really necessary to keep compatibility with such an old version?

If it is strictly required maybe what is there now helps someone else to complete it.

**Comment by jeremyevans** [comment]
It does look like you aren't calling the new method with the correct number of arguments (it still should take 2 arguments, not 5): https://github.com/fernandotcl/monkeys-audio/blob/5fe956c7e67c13daa80518a4cc7001e9fa185297/src/MACLib/MACLib.h#L423 . However, I'm not sure if that is what is causing the linker error. 

Dropping Monkey's audio support doesn't seem like a big deal, honestly.  It never had much use even in the early 2000s, and these days I doubt anyone would want to use it compared to WavPack (which came earlier) or FLAC (which came later).  The Monkey's audio decoder is also the only C++ code in Aqualung.

**Comment by billie80** [comment]
> It does look like you aren't calling the new method with the correct number of arguments (it still should take 2 arguments, not 5): https://github.com/fernandotcl/monkeys-audio/blob/5fe956c7e67c13daa80518a4cc7001e9fa185297/src/MACLib/MACLib.h#L423 . However, I'm not sure if that is what is causing the linker error.

I think I do. The file you are referencing must be from a really old version of Monkeys Audio. The last commit is from 2018. I am trying to make it build against a very recent version ([10.18 released 2023-08-09](https://monkeysaudio.com/files/MAC_1018_SDK.zip)). Looking at the same file it requires 5 arguments now.

> Dropping Monkey's audio support doesn't seem like a big deal, honestly. It never had much use even in the early 2000s, and these days I doubt anyone would want to use it compared to WavPack (which came earlier) or FLAC (which came later). The Monkey's audio decoder is also the only C++ code in Aqualung.

I was more thinking of just disabling it in the Gentoo Ebuild (--without-mac). It is up to you if you want to drop it completely. I thought it would make sense to keep it as it is under active [development](https://monkeysaudio.com/versionhistory.html).

**Comment by jeremyevans** [comment]
> > It does look like you aren't calling the new method with the correct number of arguments (it still should take 2 arguments, not 5): https://github.com/fernandotcl/monkeys-audio/blob/5fe956c7e67c13daa80518a4cc7001e9fa185297/src/MACLib/MACLib.h#L423 . However, I'm not sure if that is what is causing the linker error.
> 
> I think I do. The file you are referencing must be from a really old version of Monkeys Audio. The last commit is from 2018. I am trying to make it build against a very recent version ([10.18 released 2023-08-09](https://monkeysaudio.com/files/MAC_1018_SDK.zip)). Looking at the same file it requires 5 arguments now.

Ah, my mistake, I apologize for that.  They don't appear to have an open source code repository, which seems strange in the modern age for software that is supposedly open source.

> > Dropping Monkey's audio support doesn't seem like a big deal, honestly. It never had much use even in the early 2000s, and these days I doubt anyone would want to use it compared to WavPack (which came earlier) or FLAC (which came later). The Monkey's audio decoder is also the only C++ code in Aqualung.
> 
> I was more thinking of just disabling it in the Gentoo Ebuild (--without-mac). It is up to you if you want to drop it completely. I thought it would make sense to keep it as it is under active [development](https://monkeysaudio.com/versionhistory.html).

I don't have a problem keeping support for rarely used decoders, so long as such support is easy to maintain.  Dealing with backwards incompatible changes in the backend library makes such a decoder no longer easy to maintain.

Considering the situation, I'm willing to accept a non-backwards compatible pull request that works with Monkey's Audio 10.18.  I don't currently have any ideas about how to fix your linker issue, though maybe I'll have time to do some testing in early September.

**Comment by billie80** [comment]
No problem!
Would be great if you could find the time to look into it. No hurry though.
I will also let you know if there is progress from my side.

**Comment by billie80** [comment]
I found the issue causing the linker to fail. How could it work if you are not actually trying to link to the library. :-) I missed changing $(mac_LIBS) to upper case in Makefile.am.

[aqualung-1.2-mac-configure.patch.txt](https://github.com/jeremyevans/aqualung/files/12331928/aqualung-1.2-mac-configure.patch.txt)

However trying to play a file in aqualung generated with version 10.18 does not work. On the command line I get:
> [ape @ 0x7f4b64005080] Got unexpected packet size after a partial decode

When compiling aqualung against the old version the file generated with new version played fine.

I forked the project and created a [commit](https://github.com/billie80/aqualung/commit/a4571bfdb1d92757308d96801503c46823caed29) with the current changes. As it is not functional I don't think a pull request makes sense at the moment, but this way it is easier to review the changes compared to the attachments here.

**Comment by jeremyevans** [comment]
Thanks for your patience.  I finally had time to look into the issue.  It appears the problem is due to wrong endianness of filename character encoding. Once that is fixed, it works correctly.  The `Got unexpected packet size after a partial decode` message is a red herring, that comes from the lavc decoder after the mac decoder cannot handle it.  I'll merge your patch and add the fix on top of it.  Thank you for working on this!

**Comment by billie80** [comment]
Hey Jeremy!
This is great. I have to thank you for taking the time to figure this out.
Only one thing. I might be wrong but with your change the include of [glib.h](https://github.com/jeremyevans/aqualung/commit/a991c13d0df734a5d0fea7db6b181176858f3e58#diff-97e2c31871cfe106558623ea60692a9c6f6fa6d59d46579eb542f868d27bf444R27) I introduced might not be necessary then.

**Comment by jeremyevans** [comment]
@billie80 Thanks for testing and pointing out the glib include was now unnecessary.  I pushed a commit to remove the glib include.
