### ISSUE TITLE
add .m4a to lavc so it shows in the default of All audio files in gui

### ISSUE THREAD

**Issue by mc4man** [jeremyevans/aqualung#6]
Minor issue, something like 
@@ -499,7 +499,7 @@ assign_audio_fc_filters(GtkFileChooser *
         gtk_file_filter_set_name(filter, _("LAVC audio/video files"));
 	{
 		char * valid_ext_lavc[] = {
-			"aac", "ac3", "asf", "avi", "mpeg", "mpg", "mp3", "ra",
+			"aac", "ac3", "asf", "avi", "m4a", "mpeg", "mpg", "mp3", "ra",
 			"wav", "wma", "wv", NULL };
 		build_filter_from_extensions(filter, filter_all, valid_ext_lavc);
 	}

**Comment by jeremyevans** [comment]
This makes sense to me, I'll work on it shortly.
