### ISSUE TITLE
Possible to run headless?

### ISSUE THREAD

**Issue by ckemere** [jeremyevans/aqualung#7]
Hi,

I'm setting up a raspberry pi based audio project where I wanted to be able to loop audio files in a gapless manner. Aqualung works really nicely for this, but I'd love to be able to use it without having to run X. Are there any secret command line options to allow it to work without starting the GUI?

thanks!

**Comment by jeremyevans** [comment]
I don't believe it is possible to run aqualung without X, but you could probably use a headless X server (e.g. Xvfb).
