### ISSUE TITLE
timer display

### ISSUE THREAD

**Issue by ronchon65** [jeremyevans/aqualung#9]
Hello,
I used Aqualung for years and I really like it !
Recently I got timer display problems and I don't clearly see where they come from (see screen capture).
Any indication ? Thanks in advance !
My system is Debian 5.7.6-1 (2020-06-24) x86_64 GNU/Linux.
![aqualung-pb](https://user-images.githubusercontent.com/43472511/87226051-865ae700-c391-11ea-87d3-45897f523922.png)

**Comment by jeremyevans** [comment]
I think this is an issue with the plain skin.  Can you try one of the other skins (such as the default skin) and see if it goes away?

**Comment by ronchon65** [comment]
Le 2020-07-11 17:59, Jeremy Evans a écrit :

> I think this is an issue with the plain skin. Can you try one of the other skins (such as the default skin) and see if it goes away? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

Thanks for your answer ! 

No change with another skin... I first suspected a problem with locales,
but these characters are only digits, normally the locale wouldn't
matter... 

-- GD. 

Links:
------
[1]
https://github.com/jeremyevans/aqualung/issues/9#issuecomment-657085810
[2]

**Comment by jeremyevans** [comment]
Can you go to Settings->Appearance->Fonts, and for the Big timer and Small timers, select an appropriate font, and see if that fixes it?

**Comment by jeremyevans** [comment]
You might have to click the override skin settings checkbox to be able to edit the fonts.

**Comment by ronchon65** [comment]
Le 2020-07-11 21:14, Jeremy Evans a écrit :

> Can you go to Settings->Appearance->Fonts, and for the Big timer and Small timers, select an appropriate font, and see if that fixes it? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

OK, changing the fonts solves the problem ! I didn't take sufficient
care of these options... 

Thanks for your help ! 

Best regards. 

-- GD. 

Links:
------
[1]
https://github.com/jeremyevans/aqualung/issues/9#issuecomment-657114435
[2]

**Comment by jeremyevans** [comment]
Great! I'm glad that fixed it.
